import './globals.css'
import { Inter } from 'next/font/google'
import {
  FpjsProvider as Provider,
} from '@fingerprintjs/fingerprintjs-pro-react'
import Footer from '@/components/Footer/page'
import Navbar from '@/components/Navbar/page'
import Banner from '@/components/banner'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Car Management System',
  description: 'Generated by Joseph',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={inter.className}>
          <div className="container">
            <Navbar/>
            {/* <FpjsProvider
loadOptions={{
  apiKey: process.env.PUBLIC_API_KEY,
  // endpoint: ["<CUSTOM_ENDPOINT>", defaultEndpoint],
  // scriptUrlPattern: ["<CUSTOM_SCRIPT_URL>", defaultScriptUrlPattern],
  // region: "eu"
}}
>
</FpjsProvider> */}
            <Provider loadOptions={{apiKey:'HN4NqtebLvejzHz6BBuA', region:'eu'}}>

            </Provider>
            <Banner></Banner>
            {children}
            <Footer/>
          </div>
    </body>
  </html>
  )
}



// export const MyApp = ({Component, pageProps}) =>{
//   return (
//     <FpjsProvider
//       loadOptions={{
//         apiKey: process.env.PUBLIC_API_KEY,
//         // endpoint: ["<CUSTOM_ENDPOINT>", defaultEndpoint],
//         // scriptUrlPattern: ["<CUSTOM_SCRIPT_URL>", defaultScriptUrlPattern],
//         // region: "eu"
//       }}
//     >
//       <Component {...pageProps} />
//     </FpjsProvider>
//   )
// }

